version: '3.1'
services:
  nginx:
    image: 'yobasystems/alpine-nginx'
    command:
      [
        'nginx',
        '-g',
        'daemon off;',
        '-c',
        '/var/nginx.conf'
      ]
    ports:
      - '8041:8041' # Move to IP:Port to bind only to a particular IP, e.g. 123.123.123.123:8041:8041
    volumes:
      - "/etc/scion/certs:/srv/http/"
      - "/etc/scion/topology.json:/srv/http/topology.json"
      - "./data/trcs.json:/srv/http/trcs.json"
      - "./nginx.conf:/var/nginx.conf"
  file-watcher:
    build: .
    volumes:
      - /etc/scion/certs:/etc/scion/certs
      - ./data/:/etc/scion/bootstrap-server/